-- Seeds: Amostra de cartas de Tarot (apenas Arcanos Maiores para demonstração)

WITH tarot AS (SELECT id FROM public.oracles WHERE slug = 'tarot' LIMIT 1)
INSERT INTO public.oracle_cards (oracle_id, code, name, number, suit, keywords, description) VALUES
  ((SELECT id FROM tarot), 'arcano_0', 'O Louco', 0, 'arcanos_maiores', ARRAY['inicio', 'espontaneidade', 'confianca', 'jornada'], 'O Louco representa o início de uma jornada, a confiança cega no universo e a pureza das intenções. É o espírito livre que salta para o desconhecido.' || chr(10) || 'Palavras-chave: novos começos, inocência, aventura, potencial infinito.'),
  ((SELECT id FROM tarot), 'arcano_1', 'O Mago', 1, 'arcanos_maiores', ARRAY['poder', 'manifestacao', 'habilidade', 'vontade'], 'O Mago é o canal entre o divino e o terreno. Com as ferramentas nos quatro elementos, ele manifesta a realidade através da vontade consciente.' || chr(10) || 'Palavras-chave: poder pessoal, criatividade, habilidade, foco.'),
  ((SELECT id FROM tarot), 'arcano_2', 'A Sacerdotisa', 2, 'arcanos_maiores', ARRAY['intuicao', 'mistério', 'sabedoria', 'subconsciente'], 'A Sacerdotisa guarda os mistérios do subconsciente e do conhecimento oculto. Ela representa a intuição silenciosa que sabe sem precisar provar.' || chr(10) || 'Palavras-chave: intuição, mistério, sabedoria interior, potencial oculto.'),
  ((SELECT id FROM tarot), 'arcano_3', 'A Imperatriz', 3, 'arcanos_maiores', ARRAY['natureza', 'abundancia', 'fertilidade', 'beleza'], 'A Imperatriz é a mãe natureza em sua plenitude. Representa abundância, sensualidade, criatividade e a conexão com os ciclos naturais da vida.' || chr(10) || 'Palavras-chave: abundância, fertilidade, natureza, beleza.'),
  ((SELECT id FROM tarot), 'arcano_4', 'O Imperador', 4, 'arcanos_maiores', ARRAY['autoridade', 'estrutura', 'poder', 'disciplina'], 'O Imperador representa a autoridade justa, a estrutura sólida e o poder que protege e organiza. É o pai que estabelece as leis e os limites.' || chr(10) || 'Palavras-chave: autoridade, estrutura, proteção, disciplina.'),
  ((SELECT id FROM tarot), 'arcano_5', 'O Hierofante', 5, 'arcanos_maiores', ARRAY['tradicao', 'ensino', 'ritual', 'conhecimento'], 'O Hierofante é o guardião da sabedoria sagrada e dos rituais tradicionais. Representa o ensino formal, a orientação espiritual e os dogmas que estruturam a fé.' || chr(10) || 'Palavras-chave: tradição, ensino, ritual, orientação espiritual.'),
  ((SELECT id FROM tarot), 'arcano_6', 'Os Enamorados', 6, 'arcanos_maiores', ARRAY['amor', 'escolha', 'uniao', 'valores'], 'Os Enamorados representam a escolha consciente guiada pelo coração. É a união dos opostos, o amor como força criativa e a decisão que alinha coração e alma.' || chr(10) || 'Palavras-chave: amor, escolha, união, alinhamento.'),
  ((SELECT id FROM tarot), 'arcano_7', 'O Carro', 7, 'arcanos_maiores', ARRAY['vitoria', 'determinacao', 'controle', 'vontade'], 'O Carro é a vitória da vontade sobre as forças opostas. Representa determinação, controle emocional e a capacidade de superar obstáculos através do foco.' || chr(10) || 'Palavras-chave: vitória, determinação, controle, superação.'),
  ((SELECT id FROM tarot), 'arcano_8', 'A Força', 8, 'arcanos_maiores', ARRAY['coragem', 'força_interior', 'domesticacao', 'paixao'], 'A Força não é poder bruto, mas a coragem gentil de domar a fera interior. Representa a força tranquila que vem da paciência, compaixão e autocontrole.' || chr(10) || 'Palavras-chave: coragem, força interior, paciência, compaixão.'),
  ((SELECT id FROM tarot), 'arcano_9', 'O Eremita', 9, 'arcanos_maiores', ARRAY['introspecao', 'solidao', 'sabedoria', 'luz_interior'], 'O Eremita busca a verdade nas profundezas do silêncio. Com sua lanterna, ilumina os caminhos escuros da alma, guiando através da solidão criativa.' || chr(10) || 'Palavras-chave: introspecção, solidão, sabedoria, busca interior.'),
  ((SELECT id FROM tarot), 'arcano_10', 'A Roda da Fortuna', 10, 'arcanos_maiores', ARRAY['destino', 'ciclos', 'mudanca', 'sorte'], 'A Roda da Fortuna representa os ciclos inevitáveis da vida, a mudança constante e as voltas do destino. Lembra que tudo sobe e desce em seu tempo sagrado.' || chr(10) || 'Palavras-chave: ciclos, mudança, destino, renovação.'),
  ((SELECT id FROM tarot), 'arcano_11', 'A Justiça', 11, 'arcanos_maiores', ARRAY['justiça', 'equilibrio', 'verdade', 'causa_efeito'], 'A Justiça é a lei de causa e efeito em ação. Representa o equilíbrio cósmico, a verdade que emerge e a necessidade de assumir responsabilidade por suas ações.' || chr(10) || 'Palavras-chave: justiça, equilíbrio, verdade, responsabilidade.')
ON CONFLICT (oracle_id, code) DO NOTHING;
