-- Seeds: Tarot Arcanos Maiores (cartas 12 a 21)

WITH tarot AS (SELECT id FROM public.oracles WHERE slug = 'tarot' LIMIT 1)
INSERT INTO public.oracle_cards (oracle_id, code, name, number, suit, keywords, description) VALUES
  ((SELECT id FROM tarot), 'arcano_12', 'O Enforcado', 12, 'arcanos_maiores', ARRAY['sacrificio', 'renuncia', 'pausa', 'nova_perspectiva'], 'O Enforcado representa a pausa voluntária e o sacrifício que traz uma nova visão de mundo. Pendurado de cabeça para baixo, ele enxerga a realidade de um ângulo completamente diferente.' || chr(10) || 'Palavras-chave: sacrifício, renúncia, pausa, nova perspectiva.'),
  ((SELECT id FROM tarot), 'arcano_13', 'A Morte', 13, 'arcanos_maiores', ARRAY['transformacao', 'renovacao', 'fim_ciclo', 'transicao'], 'A Morte não é um fim definitivo, mas a transformação profunda que dissolve o velho para dar espaço ao novo. Representa o encerramento de ciclos e o renascimento inevitável.' || chr(10) || 'Palavras-chave: transformação, renovação, fim de ciclo, transição.'),
  ((SELECT id FROM tarot), 'arcano_14', 'A Temperança', 14, 'arcanos_maiores', ARRAY['equilibrio', 'moderacao', 'paciencia', 'harmonia'], 'A Temperança é a arte de encontrar equilíbrio entre extremos, combinando opostos com paciência e serenidade. Representa a cura pela moderação e a alquimia interior que harmoniza corpo, mente e espírito.' || chr(10) || 'Palavras-chave: equilíbrio, moderação, paciência, harmonia.'),
  ((SELECT id FROM tarot), 'arcano_15', 'O Diabo', 15, 'arcanos_maiores', ARRAY['sombra', 'tentacao', 'materia', 'apego'], 'O Diabo simboliza as amarras que criamos a partir de nossos apegos materiais e medos mais profundos. Representa a sombra que precisa ser confrontada para que possamos nos libertar das correntes que nós mesmos forjamos.' || chr(10) || 'Palavras-chave: sombra, tentação, matéria, apego.'),
  ((SELECT id FROM tarot), 'arcano_16', 'A Torre', 16, 'arcanos_maiores', ARRAY['ruptura', 'revelacao', 'colapso', 'verdade'], 'A Torre é a derrubada das estruturas ilusórias que construímos sobre falsas fundações. Embora violenta, sua destruição traz a revelação da verdade e a libertação necessária para reconstruir sobre bases sólidas.' || chr(10) || 'Palavras-chave: ruptura, revelação, colapso, verdade.'),
  ((SELECT id FROM tarot), 'arcano_17', 'A Estrela', 17, 'arcanos_maiores', ARRAY['esperanca', 'inspiracao', 'cura', 'serenidade'], 'A Estrela é a luz de esperança que brilha após a tempestade, trazendo cura e renovação espiritual. Representa a conexão com o divino, a inspiração que guia e a serenidade de confiar no fluxo do universo.' || chr(10) || 'Palavras-chave: esperança, inspiração, cura, serenidade.'),
  ((SELECT id FROM tarot), 'arcano_18', 'A Lua', 18, 'arcanos_maiores', ARRAY['ilusao', 'medo', 'subconsciente', 'intuicao'], 'A Lua reflete a luz incerta do subconsciente, onde habitam medos, ilusões e intuições profundas. Convida a navegar pelas águas escuras da psique com confiança, revelando que nem tudo é o que parece.' || chr(10) || 'Palavras-chave: ilusão, medo, subconsciente, intuição.'),
  ((SELECT id FROM tarot), 'arcano_19', 'O Sol', 19, 'arcanos_maiores', ARRAY['alegria', 'sucesso', 'vitalidade', 'realizacao'], 'O Sol é a radiância da alegria plena, do sucesso conquistado e da vitalidade que aquece o coração. Representa a clareza absoluta, a realização dos objetivos e a celebração da vida em sua expressão mais luminosa.' || chr(10) || 'Palavras-chave: alegria, sucesso, vitalidade, realização.'),
  ((SELECT id FROM tarot), 'arcano_20', 'O Julgamento', 20, 'arcanos_maiores', ARRAY['renascimento', 'chamado', 'avaliacao', 'despertar'], 'O Julgamento é o chamado interior que nos desperta para um novo propósito, convocando-nos a avaliar o passado e renascer para uma vida mais autêntica. Representa o despertar da consciência e a absolvição que vem da autoavaliação sincera.' || chr(10) || 'Palavras-chave: renascimento, chamado, avaliação, despertar.'),
  ((SELECT id FROM tarot), 'arcano_21', 'O Mundo', 21, 'arcanos_maiores', ARRAY['completude', 'realizacao', 'integracao', 'plenitude'], 'O Mundo é a conclusão bem-sucedida de uma grande jornada, a integração de todas as experiências em unidade e plenitude. Representa a realização completa, o ciclo que se fecha em harmonia e a celebração da totalidade do ser.' || chr(10) || 'Palavras-chave: completude, realização, integração, plenitude.')
ON CONFLICT (oracle_id, code) DO NOTHING;
