-- Seeds: Tarot Arcanos Menores (56 cartas: Copas, Espadas, Ouros, Paus)

WITH tarot AS (SELECT id FROM public.oracles WHERE slug = 'tarot' LIMIT 1)
INSERT INTO public.oracle_cards (oracle_id, code, name, number, suit, keywords, description) VALUES
  -- COPAS (Ace a King)
  ((SELECT id FROM tarot), 'copas_1', 'Ás de Copas', 1, 'copas', ARRAY['amor', 'emocao', 'fertilidade', 'abertura'], 'O Ás de Copas representa o início de um novo ciclo emocional, a abertura do coração para o amor e a plenitude dos sentimentos.' || chr(10) || 'Palavras-chave: amor, emoção, fertilidade, abertura.'),
  ((SELECT id FROM tarot), 'copas_2', 'Dois de Copas', 2, 'copas', ARRAY['uniao', 'parceria', 'amor', 'conexao'], 'O Dois de Copas simboliza a união de almas, o amor romântico e as parcerias baseadas no respeito mútuo.' || chr(10) || 'Palavras-chave: união, parceria, amor, conexão.'),
  ((SELECT id FROM tarot), 'copas_3', 'Três de Copas', 3, 'copas', ARRAY['amizade', 'celebracao', 'alegria', 'comunidade'], 'O Três de Copas celebra a amizade, a alegria compartilhada e a união de grupos que celebram a vida juntos.' || chr(10) || 'Palavras-chave: amizade, celebração, alegria, comunidade.'),
  ((SELECT id FROM tarot), 'copas_4', 'Quatro de Copas', 4, 'copas', ARRAY['apatia', 'contemplacao', 'tedio', 'introspeccao'], 'O Quatro de Copas indica um momento de introspecção e apatia, onde o indivíduo se fecha para novas oportunidades emocionais.' || chr(10) || 'Palavras-chave: apatia, contemplação, tédio, introspecção.'),
  ((SELECT id FROM tarot), 'copas_5', 'Cinco de Copas', 5, 'copas', ARRAY['perda', 'tristeza', 'luto', 'desilusao'], 'O Cinco de Copas fala sobre a dor da perda e a tristeza, mas também lembra que ainda há boas coisas ao redor.' || chr(10) || 'Palavras-chave: perda, tristeza, luto, desilusão.'),
  ((SELECT id FROM tarot), 'copas_6', 'Seis de Copas', 6, 'copas', ARRAY['nostalgia', 'memorias', 'infancia', 'inocencia'], 'O Seis de Copas traz a energia da nostalgia, das lembranças felizes do passado e da pureza da infância.' || chr(10) || 'Palavras-chave: nostalgia, memórias, infância, inocência.'),
  ((SELECT id FROM tarot), 'copas_7', 'Sete de Copas', 7, 'copas', ARRAY['ilusao', 'escolhas', 'fantasias', 'confusao'], 'O Sete de Copas alerta sobre as ilusões e fantasias que podem confundir o julgamento e afastar da realidade.' || chr(10) || 'Palavras-chave: ilusão, escolhas, fantasias, confusão.'),
  ((SELECT id FROM tarot), 'copas_8', 'Oito de Copas', 8, 'copas', ARRAY['desapego', 'busca', 'afastamento', 'renovacao'], 'O Oito de Copas representa o momento de abandonar o que não serve mais e buscar um propósito maior.' || chr(10) || 'Palavras-chave: desapego, busca, afastamento, renovação.'),
  ((SELECT id FROM tarot), 'copas_9', 'Nove de Copas', 9, 'copas', ARRAY['satisfacao', 'realizacao', 'felicidade', 'desejos'], 'O Nove de Copas é o desejo realizado, a satisfação pessoal e a felicidade plena que vem da conquista emocional.' || chr(10) || 'Palavras-chave: satisfação, realização, felicidade, desejos.'),
  ((SELECT id FROM tarot), 'copas_10', 'Dez de Copas', 10, 'copas', ARRAY['felicidade_plena', 'familia', 'harmonia', 'amor_duradouro'], 'O Dez de Copas representa a felicidade familiar, o amor incondicional e a harmonia plena nos relacionamentos.' || chr(10) || 'Palavras-chave: felicidade plena, família, harmonia, amor duradouro.'),
  ((SELECT id FROM tarot), 'copas_11', 'Valete de Copas', 11, 'copas', ARRAY['jovem_emocional', 'intuicao', 'criatividade', 'mensagem'], 'O Valete de Copas traz uma mensagem de amor ou criatividade, representando um jovem sensível e intuitivo.' || chr(10) || 'Palavras-chave: jovem emocional, intuição, criatividade, mensagem.'),
  ((SELECT id FROM tarot), 'copas_12', 'Cavaleiro de Copas', 12, 'copas', ARRAY['idealismo', 'romantismo', 'convite', 'amor'], 'O Cavaleiro de Copas é o romântico idealista que oferece seu coração e segue em direção aos seus sonhos emocionais.' || chr(10) || 'Palavras-chave: idealismo, romantismo, convite, amor.'),
  ((SELECT id FROM tarot), 'copas_13', 'Rainha de Copas', 13, 'copas', ARRAY['empatia', 'cuidado', 'intuicao', 'amor_materno'], 'A Rainha de Copas é a curadora emocional, a mulher intuitiva que cuida com amor e compreensão profunda.' || chr(10) || 'Palavras-chave: empatia, cuidado, intuição, amor materno.'),
  ((SELECT id FROM tarot), 'copas_14', 'Rei de Copas', 14, 'copas', ARRAY['maturidade_emocional', 'compaixao', 'sabedoria', 'controle'], 'O Rei de Copas domina suas emoções com sabedoria e compaixão, oferecendo conselho e estabilidade emocional.' || chr(10) || 'Palavras-chave: maturidade emocional, compaixão, sabedoria, controle.'),

  -- ESPADAS (Ace a King)
  ((SELECT id FROM tarot), 'espadas_1', 'Ás de Espadas', 1, 'espadas', ARRAY['clareza_mental', 'verdade', 'justica', 'intelecto'], 'O Ás de Espadas simboliza o poder da mente, a clareza absoluta e o corte da verdade que liberta.' || chr(10) || 'Palavras-chave: clareza mental, verdade, justiça, intelecto.'),
  ((SELECT id FROM tarot), 'espadas_2', 'Dois de Espadas', 2, 'espadas', ARRAY['decisao_dificil', 'impasse', 'equilibrio', 'bloqueio'], 'O Dois de Espadas representa a necessidade de tomar uma decisão difícil, equilibrando forças opostas com a mente.' || chr(10) || 'Palavras-chave: decisão difícil, impasse, equilíbrio, bloqueio.'),
  ((SELECT id FROM tarot), 'espadas_3', 'Três de Espadas', 3, 'espadas', ARRAY['dor', 'sofrimento', 'traicao', 'desgosto'], 'O Três de Espadas fala sobre a dor do coração partido, o sofrimento emocional e a traição que fere profundamente.' || chr(10) || 'Palavras-chave: dor, sofrimento, traição, desgosto.'),
  ((SELECT id FROM tarot), 'espadas_4', 'Quatro de Espadas', 4, 'espadas', ARRAY['descanso', 'meditacao', 'recuperacao', 'paz'], 'O Quatro de Espadas indica a necessidade de descanso e recuperação após um período de estresse ou conflito.' || chr(10) || 'Palavras-chave: descanso, meditação, recuperação, paz.'),
  ((SELECT id FROM tarot), 'espadas_5', 'Cinco de Espadas', 5, 'espadas', ARRAY['conflito', 'derrota', 'perda', 'discordancia'], 'O Cinco de Espadas alerta para conflitos onde ninguém vence verdadeiramente, trazendo perda e amargura.' || chr(10) || 'Palavras-chave: conflito, derrota, perda, discordância.'),
  ((SELECT id FROM tarot), 'espadas_6', 'Seis de Espadas', 6, 'espadas', ARRAY['transicao', 'mudanca', 'viagem', 'deixar_ir'], 'O Seis de Espadas representa a travessia para águas mais calmas, a transição necessária e o movimento em direção à paz.' || chr(10) || 'Palavras-chave: transição, mudança, viagem, deixar ir.'),
  ((SELECT id FROM tarot), 'espadas_7', 'Sete de Espadas', 7, 'espadas', ARRAY['engano', 'estrategia', 'fuga', 'segredo'], 'O Sete de Espadas alerta para enganos, trapaças e estratégias ocultas, ou a necessidade de agir com discrição.' || chr(10) || 'Palavras-chave: engano, estratégia, fuga, segredo.'),
  ((SELECT id FROM tarot), 'espadas_8', 'Oito de Espadas', 8, 'espadas', ARRAY['prisao_mental', 'limitacao', 'medo', 'impotencia'], 'O Oito de Espadas mostra a sensação de estar preso em pensamentos limitantes e medos que paralisam.' || chr(10) || 'Palavras-chave: prisão mental, limitação, medo, impotência.'),
  ((SELECT id FROM tarot), 'espadas_9', 'Nove de Espadas', 9, 'espadas', ARRAY['ansiedade', 'pesadelos', 'preocupacao', 'desespero'], 'O Nove de Espadas é a carta da ansiedade extrema, dos medos noturnos e da preocupação que consome a mente.' || chr(10) || 'Palavras-chave: ansiedade, pesadelos, preocupação, desespero.'),
  ((SELECT id FROM tarot), 'espadas_10', 'Dez de Espadas', 10, 'espadas', ARRAY['fim', 'derrota', 'recomeco', 'libertacao'], 'O Dez de Espadas marca o fim de um ciclo doloroso, a derrota necessária para um novo começo libertador.' || chr(10) || 'Palavras-chave: fim, derrota, recomeço, libertação.'),
  ((SELECT id FROM tarot), 'espadas_11', 'Valete de Espadas', 11, 'espadas', ARRAY['ideias_novas', 'comunicacao', 'curiosidade', 'vigilancia'], 'O Valete de Espadas traz ideias frescas e comunicação rápida, mas alerta para pensamentos dispersos.' || chr(10) || 'Palavras-chave: ideias novas, comunicação, curiosidade, vigilância.'),
  ((SELECT id FROM tarot), 'espadas_12', 'Cavaleiro de Espadas', 12, 'espadas', ARRAY['acao_urgente', 'determinacao', 'ambicao', 'impulso'], 'O Cavaleiro de Espadas avança com rapidez e determinação, cortando obstáculos com sua mente afiada.' || chr(10) || 'Palavras-chave: ação urgente, determinação, ambição, impulso.'),
  ((SELECT id FROM tarot), 'espadas_13', 'Rainha de Espadas', 13, 'espadas', ARRAY['clareza', 'verdade', 'objetividade', 'independencia'], 'A Rainha de Espadas vê a verdade nua e crua, comunicando com honestidade e independência intelectual.' || chr(10) || 'Palavras-chave: clareza, verdade, objetividade, independência.'),
  ((SELECT id FROM tarot), 'espadas_14', 'Rei de Espadas', 14, 'espadas', ARRAY['autoridade_mental', 'etica', 'comando', 'verdade'], 'O Rei de Espadas é o mestre do intelecto, que governa com ética, verdade e clareza de pensamento.' || chr(10) || 'Palavras-chave: autoridade mental, ética, comando, verdade.'),

  -- OUROS (Ace a King)
  ((SELECT id FROM tarot), 'ouros_1', 'Ás de Ouros', 1, 'ouros', ARRAY['prosperidade', 'inicio_material', 'oportunidade', 'abundancia'], 'O Ás de Ouros representa o início de um ciclo de prosperidade material, uma nova oportunidade de negócio ou abundância.' || chr(10) || 'Palavras-chave: prosperidade, início material, oportunidade, abundância.'),
  ((SELECT id FROM tarot), 'ouros_2', 'Dois de Ouros', 2, 'ouros', ARRAY['equilibrio', 'adaptacao', 'gestao', 'fluxo'], 'O Dois de Ouros fala sobre equilibrar múltiplas responsabilidades financeiras e se adaptar aos fluxos da vida.' || chr(10) || 'Palavras-chave: equilíbrio, adaptação, gestão, fluxo.'),
  ((SELECT id FROM tarot), 'ouros_3', 'Três de Ouros', 3, 'ouros', ARRAY['trabalho_equipe', 'habilidade', 'colaboracao', 'mestria'], 'O Três de Ouros celebra o trabalho em equipe, a colaboração e o desenvolvimento de habilidades profissionais.' || chr(10) || 'Palavras-chave: trabalho em equipe, habilidade, colaboração, mestria.'),
  ((SELECT id FROM tarot), 'ouros_4', 'Quatro de Ouros', 4, 'ouros', ARRAY['seguranca', 'posse', 'estabilidade', 'apego'], 'O Quatro de Ouros representa a busca por segurança material e estabilidade, mas alerta para o apego excessivo.' || chr(10) || 'Palavras-chave: segurança, posse, estabilidade, apego.'),
  ((SELECT id FROM tarot), 'ouros_5', 'Cinco de Ouros', 5, 'ouros', ARRAY['escassez', 'dificuldade', 'pobreza', 'isolamento'], 'O Cinco de Ouros fala sobre dificuldades materiais, sensação de escassez e exclusão social.' || chr(10) || 'Palavras-chave: escassez, dificuldade, pobreza, isolamento.'),
  ((SELECT id FROM tarot), 'ouros_6', 'Seis de Ouros', 6, 'ouros', ARRAY['generosidade', 'caridade', 'partilha', 'ajuda'], 'O Seis de Ouros representa a generosidade, a partilha de recursos e o equilíbrio entre dar e receber.' || chr(10) || 'Palavras-chave: generosidade, caridade, partilha, ajuda.'),
  ((SELECT id FROM tarot), 'ouros_7', 'Sete de Ouros', 7, 'ouros', ARRAY['paciencia', 'colheita', 'investimento', 'reflexao'], 'O Sete de Ouros fala sobre esperar pelos resultados do trabalho plantado e avaliar se o investimento valeu a pena.' || chr(10) || 'Palavras-chave: paciência, colheita, investimento, reflexão.'),
  ((SELECT id FROM tarot), 'ouros_8', 'Oito de Ouros', 8, 'ouros', ARRAY['dedicacao', 'aprendizado', 'artesanato', 'trabalho'], 'O Oito de Ouros representa o trabalho dedicado ao aperfeiçoamento de uma habilidade e a busca pela excelência.' || chr(10) || 'Palavras-chave: dedicação, aprendizado, artesanato, trabalho.'),
  ((SELECT id FROM tarot), 'ouros_9', 'Nove de Ouros', 9, 'ouros', ARRAY['luxo', 'autossuficiencia', 'conforto', 'realizacao'], 'O Nove de Ouros celebra a conquista material, o conforto e a independência financeira conquistados com esforço.' || chr(10) || 'Palavras-chave: luxo, autossuficiência, conforto, realização.'),
  ((SELECT id FROM tarot), 'ouros_10', 'Dez de Ouros', 10, 'ouros', ARRAY['riqueza', 'legado', 'heranca', 'tradicao_familiar'], 'O Dez de Ouros representa a abundância duradoura, o legado familiar e a prosperidade que atravessa gerações.' || chr(10) || 'Palavras-chave: riqueza, legado, herança, tradição familiar.'),
  ((SELECT id FROM tarot), 'ouros_11', 'Valete de Ouros', 11, 'ouros', ARRAY['estudo', 'aprendizagem', 'novidade_pratica', 'foco'], 'O Valete de Ouros é o estudante dedicado que busca aprender novas habilidades práticas para o mundo material.' || chr(10) || 'Palavras-chave: estudo, aprendizagem, novidade prática, foco.'),
  ((SELECT id FROM tarot), 'ouros_12', 'Cavaleiro de Ouros', 12, 'ouros', ARRAY['responsabilidade', 'trabalho_duro', 'perseveranca', 'rotina'], 'O Cavaleiro de Ouros avança com paciência e responsabilidade, dedicando-se ao trabalho com perseverança incansável.' || chr(10) || 'Palavras-chave: responsabilidade, trabalho duro, perseverança, rotina.'),
  ((SELECT id FROM tarot), 'ouros_13', 'Rainha de Ouros', 13, 'ouros', ARRAY['abundancia', 'natureza', 'praticidade', 'nutricao'], 'A Rainha de Ouros é a mestre da prosperidade prática, que nutre o mundo material com amor e abundância.' || chr(10) || 'Palavras-chave: abundância, natureza, praticidade, nutrição.'),
  ((SELECT id FROM tarot), 'ouros_14', 'Rei de Ouros', 14, 'ouros', ARRAY['sucesso', 'lideranca_financeira', 'abundancia', 'seguranca'], 'O Rei de Ouros é o mestre do mundo material, que alcançou sucesso e segurança através de disciplina e sabedoria.' || chr(10) || 'Palavras-chave: sucesso, liderança financeira, abundância, segurança.'),

  -- PAUS (Ace a King)
  ((SELECT id FROM tarot), 'paus_1', 'Ás de Paus', 1, 'paus', ARRAY['inspiracao', 'comeco', 'paixao', 'energia'], 'O Ás de Paus acende a chama da inspiração, o início de um projeto criativo e a paixão que impulsiona a ação.' || chr(10) || 'Palavras-chave: inspiração, começo, paixão, energia.'),
  ((SELECT id FROM tarot), 'paus_2', 'Dois de Paus', 2, 'paus', ARRAY['planejamento', 'decisao', 'futuro', 'visao'], 'O Dois de Paus fala sobre planejar o futuro, tomar decisões importantes e expandir horizontes com visão estratégica.' || chr(10) || 'Palavras-chave: planejamento, decisão, futuro, visão.'),
  ((SELECT id FROM tarot), 'paus_3', 'Três de Paus', 3, 'paus', ARRAY['expansao', 'progresso', 'exploracao', 'oportunidades'], 'O Três de Paus indica que os planos estão dando frutos, com oportunidades de expansão e progresso no horizonte.' || chr(10) || 'Palavras-chave: expansão, progresso, exploração, oportunidades.'),
  ((SELECT id FROM tarot), 'paus_4', 'Quatro de Paus', 4, 'paus', ARRAY['celebracao', 'lar', 'alegria', 'conquista'], 'O Quatro de Paus celebra a conquista de um lar ou projeto, a alegria da estabilidade e as festividades familiares.' || chr(10) || 'Palavras-chave: celebração, lar, alegria, conquista.'),
  ((SELECT id FROM tarot), 'paus_5', 'Cinco de Paus', 5, 'paus', ARRAY['competicao', 'conflito', 'disputa', 'tensao'], 'O Cinco de Paus representa a competição acirrada, conflitos de ego e a tensão que surge de opiniões divergentes.' || chr(10) || 'Palavras-chave: competição, conflito, disputa, tensão.'),
  ((SELECT id FROM tarot), 'paus_6', 'Seis de Paus', 6, 'paus', ARRAY['vitoria', 'reconhecimento', 'sucesso', 'orgulho'], 'O Seis de Paus traz a vitória merecida, o reconhecimento público e o sucesso conquistado com esforço.' || chr(10) || 'Palavras-chave: vitória, reconhecimento, sucesso, orgulho.'),
  ((SELECT id FROM tarot), 'paus_7', 'Sete de Paus', 7, 'paus', ARRAY['desafio', 'defesa', 'perseveranca', 'coragem'], 'O Sete de Paus fala sobre defender sua posição com coragem diante dos desafios e manter-se firme.' || chr(10) || 'Palavras-chave: desafio, defesa, perseverança, coragem.'),
  ((SELECT id FROM tarot), 'paus_8', 'Oito de Paus', 8, 'paus', ARRAY['movimento', 'velocidade', 'progresso', 'comunicacao'], 'O Oito de Paus anuncia movimento rápido, progresso acelerado e notícias que chegam em alta velocidade.' || chr(10) || 'Palavras-chave: movimento, velocidade, progresso, comunicação.'),
  ((SELECT id FROM tarot), 'paus_9', 'Nove de Paus', 9, 'paus', ARRAY['resiliencia', 'persistencia', 'resistencia', 'forca'], 'O Nove de Paus representa a resiliência diante das adversidades e a força interior para continuar lutando.' || chr(10) || 'Palavras-chave: resiliência, persistência, resistência, força.'),
  ((SELECT id FROM tarot), 'paus_10', 'Dez de Paus', 10, 'paus', ARRAY['fardo', 'sobrecarga', 'responsabilidade', 'pressao'], 'O Dez de Paus alerta para o excesso de responsabilidades e o fardo pesado que pode estar sobrecarregando sua vida.' || chr(10) || 'Palavras-chave: fardo, sobrecarga, responsabilidade, pressão.'),
  ((SELECT id FROM tarot), 'paus_11', 'Valete de Paus', 11, 'paus', ARRAY['entusiasmo', 'criatividade', 'exploracao', 'mensagem'], 'O Valete de Paus traz a energia do jovem criativo e entusiasmado com novas ideias e projetos ousados.' || chr(10) || 'Palavras-chave: entusiasmo, criatividade, exploração, mensagem.'),
  ((SELECT id FROM tarot), 'paus_12', 'Cavaleiro de Paus', 12, 'paus', ARRAY['aventura', 'impulso', 'paixao', 'acao'], 'O Cavaleiro de Paus é o aventureiro apaixonado que age com impulso e coragem em busca de seus sonhos.' || chr(10) || 'Palavras-chave: aventura, impulso, paixão, ação.'),
  ((SELECT id FROM tarot), 'paus_13', 'Rainha de Paus', 13, 'paus', ARRAY['confianca', 'coragem', 'lideranca', 'criatividade'], 'A Rainha de Paus irradia confiança e calor criativo, liderando com coragem e inspirando todos ao seu redor.' || chr(10) || 'Palavras-chave: confiança, coragem, liderança, criatividade.'),
  ((SELECT id FROM tarot), 'paus_14', 'Rei de Paus', 14, 'paus', ARRAY['lideranca', 'visao', 'nobreza', 'ousadia'], 'O Rei de Paus é o líder visionário que inspira com sua ousadia, assumindo grandes responsabilidades com nobreza.' || chr(10) || 'Palavras-chave: liderança, visão, nobreza, ousadia.')
ON CONFLICT (oracle_id, code) DO NOTHING;
