-- Seeds: 24 Runas do Elder Futhark

WITH runas AS (SELECT id FROM public.oracles WHERE slug = 'runas' LIMIT 1)
INSERT INTO public.oracle_cards (oracle_id, code, name, number, suit, keywords, description) VALUES
  ((SELECT id FROM runas), 'fehu', 'Fehu (Gado)', 1, 'futhark', ARRAY['riqueza', 'abundancia', 'rebanho', 'prosperidade'], 'Fehu simboliza a riqueza móvel, o gado como medida de prosperidade e a abundância que flui através da troca justa. É a energia da posse conquistada e do recurso que alimenta a vida.' || chr(10) || 'Palavras-chave: riqueza, abundância, prosperidade, sucesso material.'),
  ((SELECT id FROM runas), 'uruz', 'Uruz (Touro)', 2, 'futhark', ARRAY['forca', 'saude', 'vitalidade', 'superacao'], 'Uruz é a força bruta do touro selvagem, a vitalidade indomável que impulsiona a transformação. Representa a saúde vigorosa e a capacidade de superar limitações físicas.' || chr(10) || 'Palavras-chave: força, vitalidade, coragem, resistência.'),
  ((SELECT id FROM runas), 'thurisaz', 'Thurisaz (Espinho)', 3, 'futhark', ARRAY['desafio', 'protecao', 'conflito', 'defesa'], 'Thurisaz é o espinho que fere e protege, o desafio que forja o caráter e a defesa que guarda o sagrado. Traz a energia do gigante que confronta para ensinar.' || chr(10) || 'Palavras-chave: desafio, proteção, conflito, defesa.'),
  ((SELECT id FROM runas), 'ansuz', 'Ansuz (Mensagem)', 4, 'futhark', ARRAY['comunicacao', 'sabedoria', 'deuses', 'inspiracao'], 'Ansuz é a runa da comunicação divina, o sopro de Odin que inspira a palavra sábia. Representa mensagens, conselhos e o poder criativo da linguagem.' || chr(10) || 'Palavras-chave: comunicação, sabedoria, inspiração, verdade.'),
  ((SELECT id FROM runas), 'raidho', 'Raidho (Jornada)', 5, 'futhark', ARRAY['viagem', 'movimento', 'caminho', 'evolucao'], 'Raidho é a jornada ritual, o caminho que se percorre com propósito e consciência. Simboliza o movimento cíclico da vida e a evolução através da experiência.' || chr(10) || 'Palavras-chave: jornada, movimento, progresso, mudança.'),
  ((SELECT id FROM runas), 'kenaz', 'Kenaz (Tocha)', 6, 'futhark', ARRAY['criatividade', 'fogo', 'iluminacao', 'paixao'], 'Kenaz é a tocha que ilumina a escuridão e o fogo da forja que transforma o metal bruto em arte. Representa a criatividade, a paixão criadora e o conhecimento que revela.' || chr(10) || 'Palavras-chave: criatividade, iluminação, paixão, transformação.'),
  ((SELECT id FROM runas), 'gebo', 'Gebo (Presente)', 7, 'futhark', ARRAY['troca', 'parceria', 'generosidade', 'equilibrio'], 'Gebo é o presente sagrado da troca equilibrada, a parceria que honra ambos os lados. Simboliza a generosidade que fortalece laços e o equilíbrio do dar e receber.' || chr(10) || 'Palavras-chave: troca, parceria, generosidade, equilíbrio.'),
  ((SELECT id FROM runas), 'wunjo', 'Wunjo (Alegria)', 8, 'futhark', ARRAY['felicidade', 'harmonia', 'bem_estar', 'realizacao'], 'Wunjo é a alegria que flui da harmonia e da realização plena. Representa o bem-estar profundo que acompanha a superação dos desafios e a união com o divino.' || chr(10) || 'Palavras-chave: alegria, harmonia, realização, contentamento.'),
  ((SELECT id FROM runas), 'hagalaz', 'Hagalaz (Granizo)', 9, 'futhark', ARRAY['destruicao', 'crise', 'transformacao', 'renovacao'], 'Hagalaz é a força incontrolável da natureza que destrói para renovar. Como o granizo que vem sem aviso, representa as crises inevitáveis que preparam o terreno para o novo.' || chr(10) || 'Palavras-chave: destruição, crise, transformação, renovação.'),
  ((SELECT id FROM runas), 'nauthiz', 'Nauthiz (Necessidade)', 10, 'futhark', ARRAY['resistencia', 'necessidade', 'urgencia', 'fe'], 'Nauthiz é a runa da necessidade que aperta e da resistência que nasce da adversidade. Ensina que a verdadeira força surge quando confrontamos nossas limitações com fé.' || chr(10) || 'Palavras-chave: necessidade, resistência, superação, fé.'),
  ((SELECT id FROM runas), 'isa', 'Isa (Gelo)', 11, 'futhark', ARRAY['paralisia', 'introspeccao', 'pausa', 'clareza'], 'Isa é o gelo que imobiliza e preserva, a pausa forçada que convida à introspecção. Representa a clareza que surge no silêncio e a sabedoria da espera consciente.' || chr(10) || 'Palavras-chave: paralisia, introspecção, pausa, clareza.'),
  ((SELECT id FROM runas), 'jera', 'Jera (Colheita)', 12, 'futhark', ARRAY['ciclo', 'recompensa', 'colheita', 'paz'], 'Jera é a colheita que chega após o trabalho paciente, o ciclo da semeadura à fruição. Simboliza a recompensa justa pelo esforço e a paz que acompanha a conclusão.' || chr(10) || 'Palavras-chave: colheita, ciclo, recompensa, paz.'),
  ((SELECT id FROM runas), 'eihwaz', 'Eihwaz (Teixo)', 13, 'futhark', ARRAY['resistencia', 'protecao', 'perseveranca', 'transcendencia'], 'Eihwaz é a árvore da vida que liga os mundos, o teixo que resiste às estações mais duras. Representa a perseverança que transcende a morte e a proteção das tradições ancestrais.' || chr(10) || 'Palavras-chave: resistência, proteção, perseverança, transcendência.'),
  ((SELECT id FROM runas), 'perthro', 'Perthro (Dados)', 14, 'futhark', ARRAY['destino', 'sorte', 'segredo', 'revelacao'], 'Perthro é o cálice do destino onde repousam as possibilidades ocultas. Representa os mistérios que se revelam no tempo certo, a sorte que acompanha o risco e os segredos do útero da criação.' || chr(10) || 'Palavras-chave: destino, sorte, mistério, revelação.'),
  ((SELECT id FROM runas), 'algiz', 'Algiz (Alce)', 15, 'futhark', ARRAY['protecao', 'defesa', 'conexao_divina', 'vigilancia'], 'Algiz é a lança erguida em defesa do sagrado, o chifre do alce que protege o território espiritual. Simboliza a conexão com os deuses e a vigilância que guarda o despertar.' || chr(10) || 'Palavras-chave: proteção, defesa, conexão divina, vigilância.'),
  ((SELECT id FROM runas), 'sowilo', 'Sowilo (Sol)', 16, 'futhark', ARRAY['vitoria', 'energia', 'sucesso', 'poder'], 'Sowilo é o sol que nunca se apaga, a vitória da luz sobre as sombras. Representa o sucesso conquistado com integridade, a energia vital e o poder que guia.' || chr(10) || 'Palavras-chave: vitória, energia, sucesso, poder.'),
  ((SELECT id FROM runas), 'tiwaz', 'Tiwaz (Justiça)', 17, 'futhark', ARRAY['honra', 'lideranca', 'sacrificio', 'ordem'], 'Tiwaz é a lança de Tyr, o deus que sacrificou a mão pela justiça e pela ordem cósmica. Representa a liderança honrada, o sacrifício pelo bem maior e a lei que sustenta o equilíbrio.' || chr(10) || 'Palavras-chave: honra, liderança, sacrifício, justiça.'),
  ((SELECT id FROM runas), 'berkana', 'Berkana (Bétula)', 18, 'futhark', ARRAY['crescimento', 'fertilidade', 'cura', 'renascimento'], 'Berkana é a bétula que renasce após o fogo, símbolo do crescimento que brota da terra fértil. Representa a cura profunda, o renascimento e o cuidado nutritivo que sustenta a vida.' || chr(10) || 'Palavras-chave: crescimento, fertilidade, cura, renascimento.'),
  ((SELECT id FROM runas), 'ehwaz', 'Ehwaz (Cavalo)', 19, 'futhark', ARRAY['parceria', 'progresso', 'confianca', 'lealdade'], 'Ehwaz é o cavalo que carrega o cavaleiro em direção ao destino, a parceria de confiança entre dois seres. Simboliza o progresso através da colaboração e a lealdade que move montanhas.' || chr(10) || 'Palavras-chave: parceria, progresso, confiança, lealdade.'),
  ((SELECT id FROM runas), 'mannaz', 'Mannaz (Humanidade)', 20, 'futhark', ARRAY['comunidade', 'identidade', 'cooperacao', 'inteligencia'], 'Mannaz é a runa da humanidade compartilhada, o laço que une todos os filhos da terra. Representa a cooperação entre iguais, a inteligência coletiva e a identidade que se descobre no outro.' || chr(10) || 'Palavras-chave: comunidade, identidade, cooperação, inteligência.'),
  ((SELECT id FROM runas), 'laguz', 'Laguz (Água)', 21, 'futhark', ARRAY['fluxo', 'intuicao', 'emocao', 'purificacao'], 'Laguz é a água que flui nos rios do inconsciente, a intuição que guia além da razão. Simboliza o fluxo emocional, a purificação da alma e a sabedoria que emerge das profundezas.' || chr(10) || 'Palavras-chave: fluxo, intuição, emoção, purificação.'),
  ((SELECT id FROM runas), 'ingwaz', 'Ingwaz (Deus Ing)', 22, 'futhark', ARRAY['potencial', 'fertilidade', 'paz_interior', 'finalizacao'], 'Ingwaz é o deus que descansa no campo fértil, o potencial que aguarda o momento de germinar. Representa a paz interior que precede a manifestação e a conclusão que inicia novo ciclo.' || chr(10) || 'Palavras-chave: potencial, fertilidade, paz interior, finalização.'),
  ((SELECT id FROM runas), 'dagaz', 'Dagaz (Dia)', 23, 'futhark', ARRAY['despertar', 'clareza', 'transformacao_positiva', 'esperanca'], 'Dagaz é a luz do amanhecer que rompe as trevas, o despertar da consciência para uma nova realidade. Simboliza a transformação positiva, a clareza súbita e a esperança que anuncia o novo dia.' || chr(10) || 'Palavras-chave: despertar, clareza, transformação, esperança.'),
  ((SELECT id FROM runas), 'othala', 'Othala (Herança)', 24, 'futhark', ARRAY['lar', 'heranca', 'tradicao', 'pertencimento'], 'Othala é a terra dos ancestrais, o lar sagrado que carregamos no sangue e na alma. Representa a herança espiritual, as tradições que nos moldam e o pertencimento à linhagem.' || chr(10) || 'Palavras-chave: lar, herança, tradição, pertencimento.')
ON CONFLICT (oracle_id, code) DO NOTHING;
