-- Seeds: 16 Orixás do Panteão Afro-Brasileiro

WITH orixas AS (SELECT id FROM public.oracles WHERE slug = 'orixas' LIMIT 1)
INSERT INTO public.oracle_cards (oracle_id, code, name, number, suit, keywords, description) VALUES
  ((SELECT id FROM orixas), 'exu', 'Exu', 1, 'fogo', ARRAY['comunicacao', 'caminhos', 'transformacao', 'movimento'], 'Exu é o mensageiro divino, senhor dos caminhos e das encruzilhadas, que guarda a comunicação entre os mundos. Sem Exu, nada se faz — ele é o movimento que inicia todas as jornadas e a chave que abre as portas para o desconhecido.' || chr(10) || 'Palavras-chave: comunicação, caminhos, transformação, movimento.'),
  ((SELECT id FROM orixas), 'ogum', 'Ogum', 2, 'ferro', ARRAY['guerra', 'luta', 'tecnologia', 'determinacao'], 'Ogum é o guerreiro incansável que forja o aço e abre clareiras na mata com sua espada. Representa a luta justa, a tecnologia como ferramenta de evolução e a determinação inabalável diante de qualquer obstáculo.' || chr(10) || 'Palavras-chave: guerra, luta, tecnologia, determinação.'),
  ((SELECT id FROM orixas), 'oxossi', 'Oxóssi', 3, 'terra', ARRAY['caca', 'natureza', 'fartura', 'sabedoria'], 'Oxóssi é o caçador sagrado que conhece os segredos das florestas e vive em harmonia com a natureza. Sua flecha certeira representa a fartura que vem do conhecimento e da paciência em buscar o que se deseja.' || chr(10) || 'Palavras-chave: caça, natureza, fartura, sabedoria.'),
  ((SELECT id FROM orixas), 'obaluae', 'Obaluaê (Omulu)', 4, 'terra', ARRAY['cura', 'doenca', 'terra', 'transmutacao'], 'Obaluaê é o senhor da terra que cura através da doença e da transmutação profunda. Vestido de palha, esconde seu rosto mas revela o poder de transformar a dor em renascimento.' || chr(10) || 'Palavras-chave: cura, doença, terra, transmutação.'),
  ((SELECT id FROM orixas), 'xango', 'Xangô', 5, 'fogo', ARRAY['justica', 'trovao', 'poder', 'equilibrio'], 'Xangô é o rei do trovão que julga com retidão e faz tremer a terra com sua justiça implacável. Seu machado de duas lâminas corta as ilusões e restaura o equilíbrio entre o bem e o mal.' || chr(10) || 'Palavras-chave: justiça, trovão, poder, equilíbrio.'),
  ((SELECT id FROM orixas), 'oxum', 'Oxum', 6, 'agua', ARRAY['amor', 'beleza', 'fertilidade', 'prosperidade'], 'Oxum é a deusa das águas doces que encanta com sua beleza e magnetismo. Representa o amor que flui e prospera, a fertilidade que nutre e a riqueza que vem da doçura e do acolhimento.' || chr(10) || 'Palavras-chave: amor, beleza, fertilidade, prosperidade.'),
  ((SELECT id FROM orixas), 'iemanja', 'Iemanjá', 7, 'agua', ARRAY['maternidade', 'mar', 'familia', 'protecao'], 'Iemanjá é a grande mãe cujo colo é o mar imenso que acolhe todos os seus filhos. Representa a proteção familiar, a força das águas salgadas e o amor incondicional que sustenta a vida.' || chr(10) || 'Palavras-chave: maternidade, mar, família, proteção.'),
  ((SELECT id FROM orixas), 'oxala', 'Oxalá', 8, 'ar', ARRAY['paz', 'criatividade', 'fe', 'sabedoria'], 'Oxalá é o pai da criação que tece a existência com paciência e sabedoria divina. Representa a paz suprema, a fé inabalável e a pureza de espírito que guia a humanidade.' || chr(10) || 'Palavras-chave: paz, criatividade, fé, sabedoria.'),
  ((SELECT id FROM orixas), 'iansa', 'Iansã (Oyá)', 9, 'ar', ARRAY['ventos', 'tempestade', 'transformacao', 'coragem'], 'Iansã é a senhora dos ventos e das tempestades que varre o velho para dar lugar ao novo. Sua coragem explosiva e seu espírito indomável inspiram a transformação radical e a libertação.' || chr(10) || 'Palavras-chave: ventos, tempestade, transformação, coragem.'),
  ((SELECT id FROM orixas), 'nana', 'Nanã', 10, 'agua', ARRAY['sabedoria', 'ancestralidade', 'paciencia', 'morte'], 'Nanã é a anciã sábia que habita o lodo primordial onde a vida nasce e para onde ela retorna. Representa a ancestralidade, a paciência dos tempos antigos e a aceitação serena da morte como parte do ciclo.' || chr(10) || 'Palavras-chave: sabedoria, ancestralidade, paciência, morte.'),
  ((SELECT id FROM orixas), 'ewa', 'Ewá', 11, 'agua', ARRAY['visao', 'clarividencia', 'beleza', 'misterio'], 'Ewá é a deusa da visão além do véu que enxerga os mistérios ocultos nas águas profundas. Sua beleza enigmática e seu olhar clarividente revelam verdades que poucos podem compreender.' || chr(10) || 'Palavras-chave: visão, clarividência, beleza, mistério.'),
  ((SELECT id FROM orixas), 'ossaim', 'Ossaim', 12, 'terra', ARRAY['folhas', 'cura', 'natureza', 'segredos'], 'Ossaim é o senhor das folhas que conhece o poder curativo de cada planta e erva da floresta. Guardião dos segredos da natureza, ensina que a cura está na simplicidade do que é verde e vivo.' || chr(10) || 'Palavras-chave: folhas, cura, natureza, segredos.'),
  ((SELECT id FROM orixas), 'oxumare', 'Oxumarê', 13, 'agua', ARRAY['arco-iris', 'renovacao', 'ciclo', 'abundancia'], 'Oxumarê é a serpente arco-íris que conecta o céu e a terra em um ciclo eterno de renovação. Representa a abundância que flui como as cores do arco-íris e a promessa de recomeço após cada tempestade.' || chr(10) || 'Palavras-chave: arco-íris, renovação, ciclo, abundância.'),
  ((SELECT id FROM orixas), 'logunede', 'Logunedé', 14, 'agua', ARRAY['riqueza', 'caca', 'equilibrio', 'juventude'], 'Logunedé é o príncipe herdeiro que herda a caça de Oxóssi e a riqueza de Oxum. Representa o equilíbrio entre a atividade e o descanso, a juventude eterna e a prosperidade que vem da sabedoria.' || chr(10) || 'Palavras-chave: riqueza, caça, equilíbrio, juventude.'),
  ((SELECT id FROM orixas), 'ibejis', 'Ibejis', 15, 'ar', ARRAY['dualidade', 'alegria', 'infancia', 'protecao'], 'Os Ibejis são os gêmeos divinos que trazem alegria e proteção a todas as crianças. Representam a dualidade sagrada, a leveza do brincar e a força que mora na união dos opostos.' || chr(10) || 'Palavras-chave: dualidade, alegria, infância, proteção.'),
  ((SELECT id FROM orixas), 'oba', 'Obá', 16, 'agua', ARRAY['lideranca', 'determinacao', 'luta', 'superacao'], 'Obá é a guerreira feroz que luta por seu espaço com honra e determinação inabalável. Representa a liderança feminina, a superação das adversidades e a força que nunca se curva diante da injustiça.' || chr(10) || 'Palavras-chave: liderança, determinação, luta, superação.')
ON CONFLICT (oracle_id, code) DO NOTHING;
